{{- if .Values.serviceAccount.create -}}
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "blackbox-scraper.fullname" . }}
  labels:
    {{- include "blackbox-scraper.labels" . | nindent 4 }}
rules:
- apiGroups:
  - ""
  resources:
  - services
  - endpoints
  - pods
  verbs:
  - get
  - list
  - watch
{{- end }}
